template = {
            "supercategory": "hand",
            "id": 1,
            "name": "hand",
            "keypoints": [
                "wrist",
                "thumb1",
                "thumb2",
                "thumb3",
                "thumb4",
                "forefinger1",
                "forefinger2",
                "forefinger3",
                "forefinger4",
                "middle_finger1",
                "middle_finger2",
                "middle_finger3",
                "middle_finger4",
                "ring_finger1",
                "ring_finger2",
                "ring_finger3",
                "ring_finger4",
                "pinky_finger1",
                "pinky_finger2",
                "pinky_finger3",
                "pinky_finger4"
            ],
            "skeleton": [
                [
                    1,
                    2
                ],
                [
                    2,
                    3
                ],
                [
                    3,
                    4
                ],
                [
                    4,
                    5
                ],
                [
                    1,
                    6
                ],
                [
                    6,
                    7
                ],
                [
                    7,
                    8
                ],
                [
                    8,
                    9
                ],
                [
                    1,
                    10
                ],
                [
                    10,
                    11
                ],
                [
                    11,
                    12
                ],
                [
                    12,
                    13
                ],
                [
                    1,
                    14
                ],
                [
                    14,
                    15
                ],
                [
                    15,
                    16
                ],
                [
                    16,
                    17
                ],
                [
                    1,
                    18
                ],
                [
                    18,
                    19
                ],
                [
                    19,
                    20
                ],
                [
                    20,
                    21
                ]
            ]
        }